name: Linting
on:
  push:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python setup
        uses: actions/setup-python@v2
      - name: pre-commit setup
        uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GH_PAT }}
